import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Benefits
 * Id: 031ee91a-5ab5-46b6-a86a-fcdbef5f394a
 * Codename: benefits
 */
export type Benefits = IContentItem<{
    /**
     * Description (rich_text)
     * Required: true
     * Id: af1881b8-78fc-497c-88e4-9c4869074a34
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * Donation Range (text)
     * Required: true
     * Id: a05fecac-e69b-4638-9eaa-b1cf56a16c3d
     * Codename: donation_range
     */
    donationRange: Elements.TextElement;

    /**
     * Image (asset)
     * Required: true
     * Id: f0cd5a47-b557-4bd9-ba73-8043271b48a7
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Related benefits (modular_content)
     * Required: false
     * Id: 95146a8c-014e-445f-a6f0-a3e57fa84f20
     * Codename: related_benefits
     */
    relatedBenefits: Elements.LinkedItemsElement<Benefits>;

    /**
     * Title (text)
     * Required: true
     * Id: 8a4bd7e8-9fc2-4bbf-85db-5a60cacbf774
     * Codename: title
     */
    title: Elements.TextElement;
}>;
