import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Link } from './link.js';

/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Call to action
 * Id: aa0dda15-7a54-58df-acc0-a926ed835ec3
 * Codename: call_to_action
 */
export type CallToAction = IContentItem<{
    /**
     * Action Label (text)
     * Required: false
     * Id: 44caa2cb-1c66-5880-9562-ab886ebf5a70
     * Codename: action_label
     */
    actionLabel: Elements.TextElement;

    /**
     * Action Type (multiple_choice)
     * Required: true
     * Id: 310614c1-2297-5e0a-830d-9ade75469014
     * Codename: action_type
     */
    actionType: Elements.MultipleChoiceElement;

    /**
     * Image (asset)
     * Required: false
     * Id: 84813d21-ef3f-59be-a9d6-bcb06b0c01ed
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Link (modular_content)
     * Required: false
     * Id: 50e54c35-6bcb-51db-803e-96be29b97280
     * Codename: link
     */
    link: Elements.LinkedItemsElement<Link>;

    /**
     * Subtitle (text)
     * Required: false
     * Id: 448ae7b6-d834-593a-9cd3-9215e305ad69
     * Codename: subtitle
     */
    subtitle: Elements.TextElement;

    /**
     * Title (text)
     * Required: false
     * Id: d3241e23-81e7-5642-b17d-75557606bac1
     * Codename: title
     */
    title: Elements.TextElement;
}>;
