import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type FAQ } from './faq.js';

/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * FAQ Group
 * Id: 6f28ac4a-d763-5916-b6e0-accb0e1c8476
 * Codename: faq_group
 */
export type FAQGroup = IContentItem<{
    /**
     * Desription (rich_text)
     * Required: false
     * Id: 73da4ef1-43df-590a-85e3-660559ec1cd0
     * Codename: desription
     */
    desription: Elements.RichTextElement;

    /**
     * FAQ Items (modular_content)
     * Required: true
     * Id: bb2e437c-1228-5175-affa-f4cff2e25ee1
     * Codename: faq_items
     */
    faqItems: Elements.LinkedItemsElement<FAQ>;

    /**
     * Image (asset)
     * Required: false
     * Id: 4bdd0085-345f-5c41-92dc-75a89c67ec3d
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Subtitle (text)
     * Required: false
     * Id: 50b7d0b8-ce36-5c99-b818-cd215c942eb1
     * Codename: subtitle
     */
    subtitle: Elements.TextElement;

    /**
     * Title (text)
     * Required: true
     * Id: 04ff89c5-c759-5233-b93a-1f8884e2e063
     * Codename: title
     */
    title: Elements.TextElement;
}>;
