import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Link } from './link.js';
import { type Metadata } from '../content-type-snippets/metadata.js';

/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Video
 * Id: 836335bb-f60d-5f49-8fcb-d37b9bb2d7a9
 * Codename: video
 */
export type Video = IContentItem<{
    /**
     * Caption (text)
     * Required: false
     * Id: a924e89c-c4b2-5180-9f70-f3fef07b8d77
     * Codename: caption
     */
    caption: Elements.TextElement;

    /**
     * Description (rich_text)
     * Required: false
     * Id: 16ec872f-ad06-58ee-ba64-bd54d5e583ef
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * Title (text)
     * Required: false
     * Id: ae723e06-3501-5c3b-9d88-f1e6cc3d4457
     * Codename: title
     */
    title: Elements.TextElement;

    /**
     * Video Link (modular_content)
     * Required: true
     * Id: 3e87ac68-2ffc-5ee8-98f7-9737c756a99f
     * Codename: video_link
     */
    videoLink: Elements.LinkedItemsElement<Link>;
}> &
    Metadata;
