/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 */
export const assetFolders = {
    /**
     * Logos
     */
    logos: {
        id: '04e8797c-51b3-420a-9d1e-42e38292197e',
        name: 'Logos',
        externalId: undefined,
        folders: {}
    },

    /**
     * People
     */
    people: {
        id: '60d97229-634a-4530-a377-3dae10a38cd7',
        name: 'People',
        externalId: undefined,
        folders: {}
    }
} as const;
