/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 */
export const roles = {
    /**
     * Project manager
     */
    projectManager: {
        codename: 'project-manager',
        id: '19d10756-f443-49ea-964e-b9f7585bc9a2',
        name: 'Project manager'
    }
} as const;
