/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 */
export const taxonomies = {
    /**
     * Organization Type
     */
    organization_type: {
        codename: 'organization_type',
        id: '43ce5ad7-3cbb-5aca-a38c-610c6c580a2f',
        externalId: '719b6228-7a63-4248-88ab-7be1a45e9655',
        name: 'Organization Type',
        terms: {
            host: {
                codename: 'host',
                id: '57e89aee-cdf0-4f06-869a-16bc13777fd6',
                externalId: undefined,
                name: 'Host',
                terms: {}
            },
            sponsor: {
                codename: 'sponsor',
                id: 'ecc5e9e9-98f3-4a4a-9f63-f9dfefd7a163',
                externalId: undefined,
                name: 'Sponsor',
                terms: {
                    bronze: {
                        codename: 'bronze',
                        id: '7506cdb2-4979-4125-840b-a777dc4f5e05',
                        externalId: undefined,
                        name: 'Bronze',
                        terms: {}
                    },
                    gold: {
                        codename: 'gold',
                        id: 'e5322cb7-2f57-4424-b839-750065cea4a1',
                        externalId: undefined,
                        name: 'Gold',
                        terms: {}
                    },
                    silver: {
                        codename: 'silver',
                        id: 'b510f422-4982-4401-bfa1-4cb86adf645c',
                        externalId: undefined,
                        name: 'Silver',
                        terms: {}
                    }
                }
            }
        }
    }
} as const;
